# Generated by Django 4.2.6 on 2023-10-22 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SayfShop', '0002_alter_product_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='date',
        ),
        migrations.AlterField(
            model_name='product',
            name='createdDate',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='img',
            field=models.ImageField(upload_to='sayfshop/images'),
        ),
    ]
