# Generated by Django 4.2.6 on 2023-10-22 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SayfShop', '0004_remove_product_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='user',
        ),
    ]
