# Generated by Django 4.2.6 on 2023-10-22 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SayfShop', '0011_alter_basket_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='createdDate',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
