# Generated by Django 4.2.6 on 2023-10-22 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SayfShop', '0013_product_month'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='month',
        ),
    ]
